# Generated by Django 2.2.5 on 2021-06-26 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=50, verbose_name='设备ID')),
                ('info', models.CharField(max_length=50, verbose_name='上报信息')),
                ('value', models.IntegerField(verbose_name='设备数值')),
                ('alert', models.IntegerField(verbose_name='是否告警')),
                ('lat', models.FloatField(verbose_name='纬度')),
                ('lng', models.FloatField(verbose_name='经度')),
                ('timestamp', models.BigIntegerField(verbose_name='上报时间')),
            ],
        ),
    ]
