# Generated by Django 2.2.5 on 2021-06-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='client_id',
            field=models.CharField(max_length=45, verbose_name='设备ID'),
        ),
    ]
