# Generated by Django 2.2.5 on 2021-06-27 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_auto_20210626_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=45, unique=True, verbose_name='设备ID')),
                ('client_name', models.CharField(max_length=50, verbose_name='设备名字')),
                ('client_declare', models.CharField(max_length=100, verbose_name='设备描述')),
                ('client_user', models.CharField(max_length=100, verbose_name='用户')),
            ],
        ),
    ]
